### ISSUE TITLE
无法成功载入Q版小人的战斗动画

### ISSUE THREAD

**Issue by HC-Mark** [Aloento/SuperSpineViewer#24]
这是我使用的拉普兰德和能天使的素材包，感谢！
[能天使.zip](https://github.com/Aloento/SuperSpineViewer/files/6199644/default.zip)
[拉普兰德.zip](https://github.com/Aloento/SuperSpineViewer/files/6199645/default.zip)

**Comment by Aloento** [comment]
Exception in thread "LWJGL Application" java.lang.RuntimeException: Region not found in atlas: F_L_Forearm (region attachment: F_L_Forearm)
	at com.esotericsoftware.SpineStandard.attachments.AtlasAttachmentLoader.newRegionAttachment(AtlasAttachmentLoader.java:18)
	at com.esotericsoftware.SpineStandard.SkeletonBinary.readAttachment(SkeletonBinary.java:976)
	at com.esotericsoftware.SpineStandard.SkeletonBinary.readSkin(SkeletonBinary.java:948)
	at com.esotericsoftware.SpineStandard.SkeletonBinary.readSkeletonData(SkeletonBinary.java:368)
	at com.QYun.Spine.Standard.loadSkel(Standard.java:135)
	at com.QYun.Spine.Standard.create(Standard.java:210)
	at com.QYun.Spine.Universal.create(Universal.java:22)
	at com.badlogic.gdx.backends.lwjgl.LwjglFXApplication.mainLoop(LwjglFXApplication.java:63)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:127)

**Comment by Aloento** [comment]
这一般是由于你提取的atlas文件有问题导致的
请尝试https://github.com/Aloento/Arknights/tree/master/angel%E8%83%BD%E5%A4%A9%E4%BD%BF/Wild/Angel_Wild_Build

**Comment by Aloento** [comment]
请务必确认你提取的atlas, png , skel文件是同一组的同一个面
