### ISSUE TITLE
v1.2.6 exe 启动报错

### ISSUE THREAD

**Issue by PaJir** [Aloento/SuperSpineViewer#30]
error.log: 
```
Exception in Application start method
java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.NoClassDefFoundError: java/util/logging/Logger
	at org.kordamp.ikonli.AbstractIkonResolver.<clinit>(AbstractIkonResolver.java:32)
	at org.kordamp.ikonli.javafx.FontIcon.setIconLiteral(FontIcon.java:232)
	at com.QYun.SuperSpineViewer.Controller.Launcher$1$1.<init>(Launcher.java:26)
	at com.QYun.SuperSpineViewer.Controller.Launcher$1.<init>(Launcher.java:24)
	at com.QYun.SuperSpineViewer.Controller.Launcher.start(Launcher.java:23)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	... 1 more
Caused by: java.lang.ClassNotFoundException: java.util.logging.Logger
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 14 more
Uncaught error fetching image:
java.lang.NullPointerException: Cannot invoke "java.net.URL.openConnection()" because "this.url" is null
	at java.desktop/sun.awt.image.URLImageSource.getConnection(URLImageSource.java:101)
	at java.desktop/sun.awt.image.URLImageSource.getDecoder(URLImageSource.java:111)
	at java.desktop/sun.awt.image.InputStreamImageSource.doFetch(InputStreamImageSource.java:263)
	at java.desktop/sun.awt.image.ImageFetcher.fetchloop(ImageFetcher.java:212)
	at java.desktop/sun.awt.image.ImageFetcher.run(ImageFetcher.java:176)
```
另外，运行jar时发现要指定skel文件，否则虽然页面打开了，但是命令行里还是会报错，用EXE4J打包jar的话，exe启动时应该默认会打开未指定的文件，所以我建议在启动时判空，并能够在启动后选择加载的文件。

**Comment by Aloento** [comment]
抱歉时隔这么久回复（，这玩意并不会自动打开某个文件，至少我这边是没写这种逻辑的。你这个报错...怎么看都像是哪个Class炸了？而且，程序打开后左边的汉堡菜单里面有按钮 open skel，是在那里打开文件的
