### ISSUE TITLE
关于使用v1.2.6源代码的问题

### ISSUE THREAD

**Issue by KernSunerI** [Aloento/SuperSpineViewer#37]
////////////////////////////////////////////////////////////////
您好，我在https://github.com/Aloento/SuperSpineViewer/releases/tag/v1.2.6
下载了您提供的Source code (zip)，即，https://github.com/Aloento/SuperSpineViewer/archive/refs/tags/v1.2.6.zip

将其解压后，加入到我的idea中。File -> Open...
将SDK切换到15。File，Project Structure...，Platform Settings，Add New SDK，Add JDK...，apply，OK。

然后运行com.QYun.SuperSpineViewer.Main时，
出现了名为QYun SoarTeam的窗体。

同时，我的idea出现了以下内容：
SuperSpineViewer已启动
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.jfoenix.adapters.ReflectionHelper (file:/C:/Users/********/.m2/repository/com/jfoenix/jfoenix/9.0.10/jfoenix-9.0.10.jar) to method java.lang.reflect.AccessibleObject.setAccessible0(boolean)
WARNING: Please consider reporting this to the maintainers of com.jfoenix.adapters.ReflectionHelper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

当我在窗体QYun SoarTeam中，点击Open Skeleton并选择一个.skel文件后，
Skel显示了.skel文件的文件名。
Atlas显示了与.skel文件同级目录的同名的.atlas文件的文件名。
但Version与FPS没有任何显示。
也没有任何画面出现在右侧。

同时，我的idea出现了以下内容：
Spine二进制版本：38
请求初始化
Exception in thread "LWJGL Application" java.lang.SecurityException: sealing violation: package org.lwjgl.opengl is sealed
	at java.base/jdk.internal.loader.BuiltinClassLoader.getAndVerifyPackage(BuiltinClassLoader.java:869)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineOrCheckPackage(BuiltinClassLoader.java:840)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.defineOrCheckPackage(ClassLoaders.java:191)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:812)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:723)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:646)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:604)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.lwjgl.opengl.ContextGL.<init>(ContextGL.java:118)
	at org.lwjgl.opengl.Pbuffer.<init>(Pbuffer.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglToJavaFX.<init>(LwjglToJavaFX.java:34)
	at com.badlogic.gdx.backends.lwjgl.LwjglFXGraphics.createDisplayPixelFormat(LwjglFXGraphics.java:176)
	at com.badlogic.gdx.backends.lwjgl.LwjglFXGraphics.setupDisplay(LwjglFXGraphics.java:88)
	at com.badlogic.gdx.backends.lwjgl.LwjglFXApplication.mainLoop(LwjglFXApplication.java:56)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:127)

我关闭了窗体QYun SoarTeam。
我的idea显示，Process finished with exit code 0

////////////////////////////////////////////////////////////////
我在idea的终端中分别执行了mvn clean与mvn package
在过程中弹出了一些WARNING，但最终的结果是，BUILD SUCCESS

然后我执行了
********\jdk-15_windows-x64_bin\jdk-15\bin\java.exe -jar ********\SuperSpineViewer-1.2.6\SuperSpineViewer-1.2.6\target\SuperSpineViewer-1.2.6.jar
出现了窗体QYun SoarTeam，在点击Open Skeleton并选择一个.skel文件后，
Version、Skel、Atlas、FPS均有显示。
右侧也出现了画面。

但我的终端出现了下面的内容：
SuperSpineViewer已启动
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.jfoenix.adapters.ReflectionHelper (file:/********/SuperSpineViewer-1.2.6/SuperSpineViewer-1.2.6/target/SuperSpineViewer-1.2.6.jar) to method java.lang.reflect.AccessibleObject.setAccessible0(boolean)
WARNING: Please consider reporting this to the maintainers of com.jfoenix.adapters.ReflectionHelper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Spine二进制版本：38
请求初始化

我关闭了窗体QYun SoarTeam。

////////////////////////////////////////////////////////////////
请问，我要如何才能解决这个问题？
如果您需要其他信息，您可以说明，我会尽力为您提供。
另外，我向您保证，我真的看不懂您写的代码。呜呜呜。

**Comment by Aloento** [comment]
因为我写这个程序的时候使用了一些非常不规范的写法，比如使用同名文件覆盖第三方jar包内容等
可以看到 package org.lwjgl.opengl is sealed 说明这个第三方包 lwjgl 是封闭的，那么按理说就不可用使用同名文件覆盖它
你看不懂我写的代码是正常的，因为这个代码我自己都觉得乱的离谱，我最近在用Java17重写它

**Comment by Aloento** [comment]
我使用的是最早期版本的JDK 15，所以是没有这个限制的，不过我想问问你拿源码做什么呢

**Comment by KernSunerI** [comment]
我最近在写一个小游戏，当我使用您的exe程序导出序列帧并用在我的程序时，我发现这些导出的素材累积后过于巨大，于是我想，既然您可以在程序中播放.skel文件，那么我使用相同的方法也是可以的。这样我就可以只保留每个素材的.atlas、.png、.skel文件，而不是其中的每个动作对应的序列帧。

于是我下载了您的源码，但我一无所获。（悲

另外，我很期待学习您的新版本。

**Comment by Aloento** [comment]
原来你是想使用LibGDX+SpineRuntime，建议直接看
https://github.com/EsotericSoftware/spine-runtimes/tree/4.0/spine-libgdx
