### ISSUE TITLE
[spine 4.0]多个问题

### ISSUE THREAD

**Issue by RookiesTwo** [Aloento/SuperSpineViewer#41]
版本：1.3.0
ffmpeg使用的是您提供的自动解压7z包里的
jvm:openjdk 19.0.2
spine:4.0.33

第一个问题：
当atlas文件中含有format:alpha的时候贴图显示错误

示例： 
[下载地址](https://1drv.ms/u/s!ArZUihWf4T2FjxgB-gSmx-RX6aa1?e=P4NSxq)
```
yunjing.png
format:Alpha    #这一行参数会导致贴图显示为黑色
size:2048,2048
filter:Linear,Linear
scale:0.3
```

第二个问题：
同样一个案例…导出时提示ffmpeg错误
部分日志：
```
Exception in thread "" java.lang.IllegalArgumentException: invalid compression level
        at java.base/java.util.zip.Deflater.setLevel(Deflater.java:397)
        at com.badlogic.gdx.graphics.PixmapIO$PNG.setCompression(PixmapIO.java:215)
        at com.badlogic.gdx.graphics.PixmapIO.writePNG(PixmapIO.java:67)
        at to.aloen.ssv.RecordFX$savePNG.run(RecordFX.java:121)
        at java.base/java.lang.VirtualThread.run(VirtualThread.java:287)
        at java.base/java.lang.VirtualThread$VThreadContinuation.lambda$new$0(VirtualThread.java:174)
        at java.base/jdk.internal.vm.Continuation.enter0(Continuation.java:327)
        at java.base/jdk.internal.vm.Continuation.enter(Continuation.java:320)
FFmpeg处理开始
FFMPEG错误，序列已导出
导出结束
```
第二个问题我不确定是不是因为ffmpeg配置导致的问题

**Comment by RookiesTwo** [comment]
删除format:Alpha一行后显示正常

**Comment by Aloento** [comment]
emmm，4.0出错是因为我也没怎么调试过（
ffmpeg估计是我改错了什么东西（

我计划后面重构整个项目，头疼（

**Comment by qwq233** [comment]
> emmm，4.0出错是因为我也没怎么调试过（ ffmpeg估计是我改错了什么东西（
> 
> 我计划后面重构整个项目，头疼（

建议规范一下commit，异常地难读。
我现在还在jdk17，所以想直接reset掉bump到19的更改手动构筑一下。
结果一堆更改杂糅在一个commit根本无从下手orz

**Comment by Aloento** [comment]
@qwq233 www, 这就是不规范项目的问题（
17 到 19 并没有修改什么内容，你可以在 170998731 找到我

**Comment by Aloento** [comment]
可以试试 2.0 版本，如果有问题欢迎随时重新打开
