### ISSUE TITLE
用java20运行1.3.0抛异常

### ISSUE THREAD

**Issue by YYuunnHHuuii** [Aloento/SuperSpineViewer#43]
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:901)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
        at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: java.lang.UnsupportedClassVersionError: to/aloen/ssv/RecordFX (class file version 63.65535) was compiled with preview features that are unsupported. This version of the Java Runtime only recognizes preview features for class file version 64.65535

今天刚装的jdk，啥也不懂，头疼。

**Comment by Aloento** [comment]
emmm，首帧输出是可能的，我过几天去做。这个报错其实是因为你没开JDK的预览功能，这不是什么重要的事情。

**Comment by YYuunnHHuuii** [comment]
> emmm，首帧输出是可能的，我过几天去做。这个报错其实是因为你没开JDK的预览功能，这不是什么重要的事情。

谢谢巨佬

**Comment by Aloento** [comment]
@HarryG55 你要不来试试

**Comment by Aloento** [comment]
后续会直接打包exe

**Comment by HarryG55** [comment]
@Aloento Alo
手上这个做完就来。
